# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/harrymaurya05/ChemistManagment/blob/master/NLPData.ipynb
"""

from google.colab import files
files.upload()

ls -lha kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

!pip install kaggle

!kaggle competitions download -c word2vec-nlp-tutorial

!ls
!unzip labeledTrainData.tsv.zip
!unzip testData.tsv.zip
!ls

import pandas as pd
#UserInfo.tsv
train=pd.read_csv('labeledTrainData.tsv',delimiter='\t',encoding='utf-8')
print(list(train.columns.values)) #file header
print(train.tail(35)) #last N rows

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import re
from bs4 import BeautifulSoup
import nltk

import os

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

def review_to_words( raw_review):
        review_text = BeautifulSoup(raw_review, features="html5lib").get_text()         # remove HTML
        letters_only = re.sub("[^a-zA-Z]", " ", review_text)            # Remove non-letters
        words = letters_only.lower().split()                            # to lower case, split to individual words
        stops = set(stopwords.words("english"))                         # in python, searching a set is much faster than searching a list, so convert the stop words to a set
        meaningful_words = [w for w in words if not w in stops]         # remove stop words
        return(" ".join( meaningful_words ))                            # Join the words back into one string separated by space, and return the result.

num_reviews = train["review"].size
print(num_reviews)
clean_train_reviews = []
for i in range( 0, num_reviews):
        clean_train_reviews.append( review_to_words( train["review"][i]))

from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 5000) 

# fit_transform() does two functions: First, it fits the model
# and learns the vocabulary; second, it transforms our training data
# into feature vectors. The input to fit_transform should be a list of 
# strings.
train_data_features = vectorizer.fit_transform(clean_train_reviews)

# Numpy arrays are easy to work with, so convert the result to an 
# array
train_data_features = train_data_features.toarray()

from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 150) 
forest = forest.fit( train_data_features, train["sentiment"] )

test = pd.read_csv("testData.tsv", header=0, delimiter="\t", \
                   quoting=3 )

num_reviews = len(test["review"])
clean_test_reviews = [] 


for i in range(0,num_reviews):
    clean_review = review_to_words( test["review"][i] )
    clean_test_reviews.append( clean_review )
    
test_data_features = vectorizer.transform(clean_test_reviews)
test_data_features = test_data_features.toarray()

result = forest.predict(test_data_features)
output = pd.DataFrame( data={"id":test["id"], "sentiment":result} )

output.to_csv( "submit.csv", index=False, quoting=3 )

